// <auto-generated />
using Dnd.Application.Main.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dnd.Application.Main.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    [Migration("20250412223711_remove_classes")]
    partial class remove_classes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dnd.Application.Main.Models.Characters.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AC = 10,
                            Level = 1,
                            Name = "Test Character",
                            Stats = "{\"Level\":1,\"Abilities\":[{\"Name\":\"Strength\",\"Score\":10,\"Modifier\":0,\"Proficient\":false,\"Skills\":[\"Athletics\"]},{\"Name\":\"Dexterity\",\"Score\":10,\"Modifier\":0,\"Proficient\":false,\"Skills\":[\"Acrobatics\",\"Stealth\",\"SleightOfHand\"]},{\"Name\":\"Constitution\",\"Score\":10,\"Modifier\":0,\"Proficient\":false,\"Skills\":[]},{\"Name\":\"Intelligence\",\"Score\":10,\"Modifier\":0,\"Proficient\":false,\"Skills\":[\"Arcana\",\"History\",\"Investigation\",\"Nature\",\"Religion\"]},{\"Name\":\"Wisdom\",\"Score\":10,\"Modifier\":0,\"Proficient\":false,\"Skills\":[\"AnimalHandling\",\"Insight\",\"Medicine\",\"Perception\",\"Survival\"]},{\"Name\":\"Charisma\",\"Score\":10,\"Modifier\":0,\"Proficient\":false,\"Skills\":[\"Deception\",\"Intimidation\",\"Performance\",\"Persuasion\"]}],\"Skills\":[{\"Name\":\"Acrobatics\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"AnimalHandling\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Arcana\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Athletics\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Deception\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"History\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Insight\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Intimidation\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Investigation\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Medicine\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Nature\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Perception\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Performance\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Persuasion\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Religion\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"SleightOfHand\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Stealth\",\"Modifier\":0,\"Proficient\":false},{\"Name\":\"Survival\",\"Modifier\":0,\"Proficient\":false}],\"ProficiencyBonus\":2}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
