// <auto-generated />
using Dnd.Application.Main.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dnd.Application.Main.Migrations
{
    [DbContext(typeof(CharacterDbContext))]
    partial class CharacterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dnd.Application.Main.Models.Characters.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<string>("ClassesJson")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StatsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AC = 10,
                            ClassesJson = "{}",
                            Level = 1,
                            Name = "Test Character",
                            StatsJson = "{\"AbilityModifiers\":{\"Strength\":0,\"Dexterity\":0,\"Constitution\":0,\"Intelligence\":0,\"Wisdom\":0,\"Charisma\":0},\"AbilityScores\":{\"Strength\":10,\"Dexterity\":10,\"Constitution\":10,\"Intelligence\":10,\"Wisdom\":10,\"Charisma\":10},\"SkillModifiers\":{\"Acrobatics\":10,\"Animal Handling\":10,\"Arcana\":10,\"Athletics\":10,\"Deception\":10,\"History\":10,\"Insight\":10,\"Intimidation\":10,\"Investigation\":10,\"Medicine\":10,\"Nature\":10,\"Perception\":10,\"Performance\":10,\"Persuasion\":10,\"Religion\":10,\"Sleight of Hand\":10,\"Stealth\":10,\"Survival\":10},\"Proficiencies\":[]}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
