GET localhost:5218/api/Characters/
Accept: application/json

###

POST localhost:5218/api/Characters
Accept: application/json
Content-Type: application/json

{
  "name": "Theodred",
  "level": 6,
  "ac": 13,
  "abilityScores": {
    "Strength": 10,
    "Dexterity": 15,
    "Constitution": 8,
    "Intelligence": 16,
    "Wisdom": 16,
    "Charisma": 17
  },
  "skillModifiers": {
    "Acrobatics": 2,
    "AnimalHandling": 3,
    "Arcana": 6,
    "Athletics": 3,
    "Deception": 3,
    "History": 3,
    "Insight": 3,
    "Intimidation": 6,
    "Investigation": 6,
    "Medicine": 3,
    "Nature": 3,
    "Perception": 3,
    "Performance": 3,
    "Persuasion": 3,
    "Religion": 6,
    "SleightOfHand": 2,
    "Stealth": 2,
    "Survival": 6
  },
  "proficiencies": ["Wisdom", "Charisma", "Arcana", "Athletics", "Intimidation", "Investigation", "Religion", "Survival"],
  "classes": {
    "warlock": 6
  }
}
###
POST localhost:5218/api/Characters
Accept: application/json
Content-Type: application/json

{
"name": "Theodred",
"level": 6,
"ac": 13,
"abilityScores": {
"Strength": 10,
"Dexterity": 15,
"Constitution": 8,
"Intelligence": 16,
"Wisdom": 16,
"Charisma": 17
},
"skillModifiers": {
"Acrobatics": 2,
"AnimalHandling": 3,
"Arcana": 6,
"Athletics": 3,
"Deception": 3,
"History": 3,
"Insight": 3,
"Intimidation": 6,
"Investigation": 6,
"Medicine": 3,
"Nature": 3,
"Perception": 3,
"Performance": 3,
"Persuasion": 3,
"Religion": 6,
"SleightOfHand": 2,
"Stealth": 2,
"Survival": 6
},
"proficiencies": ["Wisdom", "Charisma", "Arcana", "Athletics", "Intimidation", "Investigation", "Religion", "Survival"],
"classes": {
"warlock": 6
}
}


###
POST localhost:5218/api/Characters
Accept: application/json
Content-Type: application/json

{
  "name": "Vaati",
  "level": 6,
  "ac": 15,
  "abilityScores": {
    "Strength": 13,
    "Dexterity": 14,
    "Constitution": 18,
    "Intelligence": 8,
    "Wisdom": 20,
    "Charisma": 15
  },
  "skillModifiers": {
    "Acrobatics": 2,
    "AnimalHandling": 5,
    "Arcana": 2,
    "Athletics": 1,
    "Deception": 2,
    "History": -1,
    "Insight": 5,
    "Intimidation": 2,
    "Investigation": -1,
    "Medicine": 8,
    "Nature": -1,
    "Perception": 8,
    "Performance": 2,
    "Persuasion": 2,
    "Religion": 2,
    "SleightOfHand": 2,
    "Stealth": 5,
    "Survival": 5
  },
  "proficiencies": ["Wisdom", "Charisma", "Arcana", "Medicine", "Perception", "Religion", "Stealth"],
  "classes": {
    "cleric": 6
  }
}


###
POST localhost:5218/api/Characters
Accept: application/json
Content-Type: application/json

{
"name": "Hexis",
"level": 6,
"ac": 15,
"abilityScores": {
"Strength": 17,
"Dexterity": 16,
"Constitution": 14,
"Intelligence": 14,
"Wisdom": 12,
"Charisma": 11
},
"skillModifiers": {
"Acrobatics": 3,
"AnimalHandling": 1,
"Arcana": 2,
"Athletics": 6,
"Deception": 0,
"History": 2,
"Insight": 1,
"Intimidation": 3,
"Investigation": 2,
"Medicine": 1,
"Nature": 5,
"Perception": 4,
"Performance": 0,
"Persuasion": 0,
"Religion": 2,
"SleightOfHand": 3,
"Stealth": 6,
"Survival": 4
},
"proficiencies": ["Strength", "Constitution", "Athletics", "Intimidation", "Nature", "Perception", "Stealth", "Survival"],
"classes": {
"barbarian": 6
}
}


###
POST localhost:5218/api/Characters
Accept: application/json
Content-Type: application/json

{
"name": "Malik",
"level": 6,
"ac": 15,
"abilityScores": {
"Strength": 16,
"Dexterity": 15,
"Constitution": 16,
"Intelligence": 12,
"Wisdom": 10,
"Charisma": 8
},
"skillModifiers": {
"Acrobatics": 2,
"AnimalHandling": 0,
"Arcana": 1,
"Athletics": 6,
"Deception": -1,
"History": 1,
"Insight": 0,
"Intimidation": 2,
"Investigation": 4,
"Medicine": 0,
"Nature": 1,
"Perception": 3,
"Performance": -1,
"Persuasion": -1,
"Religion": -1,
"SleightOfHand": 2,
"Stealth": 5,
"Survival": 3
},
"proficiencies": ["Strength", "Dexterity", "Athletics", "Intimidation", "Investigation", "Perception", "Stealth", "Survival"],
"classes": {
"ranger": 6
}
}


###
POST localhost:5218/api/Characters
Accept: application/json
Content-Type: application/json

{
"name": "Drakus",
"level": 6,
"ac": 20,
"abilityScores": {
"Strength": 18,
"Dexterity": 18,
"Constitution": 16,
"Intelligence": 18,
"Wisdom": 11,
"Charisma": 6
},
"skillModifiers": {
"Acrobatics": 7,
"AnimalHandling": 0,
"Arcana": 7,
"Athletics": 4,
"Deception": -2,
"History": 4,
"Insight": 0,
"Intimidation": -2,
"Investigation": 7,
"Medicine": 0,
"Nature": 4,
"Perception": 3,
"Performance": -2,
"Persuasion": -2,
"Religion": 4,
"SleightOfHand": 4,
"Stealth": 4,
"Survival": 0
},
"proficiencies": ["Strength", "Constitution", "Acrobatics", "Arcana", "Investigation", "Perception"],
"classes": {
"fighter": 3,
"artificer": 3
}
}




  