@Dnd.Auth_HostAddress = http://localhost:5033

POST http://localhost:5033/login/
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

POST http://localhost:5033/login/
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "asdf"
}
